data:
  variable: pm25
  idir: data/processed/
  odir: ~/git/esowc/aq-biascorrection/models/weights_storage/
  n_prev_obs: 24
  n_future: 24
  min_station_observations: 48
models:
  - name: ElasticNet
    type: elasticnet_regressor
    model_selection: True
    model_parameters:
      alpha: [0, 0.2, 0.4, 0.5, 1]
      l1_ratio: [0, 0.25, 0.5, 0.75, 1]
    training_method:
      cv: 5
      scoring: neg_mean_absolute_error
      n_jobs: -1
      verbose: 10